// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtY9-hDfObkuylAyEUTxojR05CcxHYFUs',
    appId: '1:378871460547:web:392d1c23de3d4d9fcc6876',
    messagingSenderId: '378871460547',
    projectId: 'henna-mehandhi',
    authDomain: 'henna-mehandhi.firebaseapp.com',
    storageBucket: 'henna-mehandhi.appspot.com',
    measurementId: 'G-VNZKFNTPEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSUPWpc5xlCyaMqz-5WuY7fSkAEr6Zg0Q',
    appId: '1:378871460547:android:0848c716d352f67bcc6876',
    messagingSenderId: '378871460547',
    projectId: 'henna-mehandhi',
    storageBucket: 'henna-mehandhi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcdeMrZPM3uvhKubXog_EPu0qTD_u121c',
    appId: '1:378871460547:ios:9710aaa1e1044e0ecc6876',
    messagingSenderId: '378871460547',
    projectId: 'henna-mehandhi',
    storageBucket: 'henna-mehandhi.appspot.com',
    iosBundleId: 'com.example.mehandhi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcdeMrZPM3uvhKubXog_EPu0qTD_u121c',
    appId: '1:378871460547:ios:69ae047811aa5e8dcc6876',
    messagingSenderId: '378871460547',
    projectId: 'henna-mehandhi',
    storageBucket: 'henna-mehandhi.appspot.com',
    iosBundleId: 'com.example.mehandhi.RunnerTests',
  );
}
